#!/usr/bin/env node
/**
 * gen-env.mjs — idempotent .env generator.
 * Rule: a key is only written when it is missing BOTH from the existing .env
 * file AND from the current process environment. Existing values are never
 * modified or reordered.
 *
 * Usage: node scripts/gen-env.mjs [--dir <project-root>] [--force-missing]
 */
import { randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, appendFileSync } from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const ENV_SPEC = [
  { key: 'PORT', gen: () => '4321', note: 'HTTP port the server listens on' },
  { key: 'HOST', gen: () => '0.0.0.0', note: 'Bind address' },
  {
    key: 'SITE_URL',
    gen: () => 'http://localhost:4321',
    note: 'Public base URL used for canonical/OG links',
  },
  {
    key: 'DATABASE_PATH',
    gen: () => './data/tadquiz.sqlite',
    note: 'SQLite database file path',
  },
  {
    key: 'SESSION_SECRET',
    gen: () => randomBytes(32).toString('hex'),
    note: 'HMAC secret for admin session cookies (auto-generated)',
    secret: true,
  },
  { key: 'SESSION_TTL_HOURS', gen: () => '72', note: 'Admin session lifetime in hours' },
  {
    key: 'GRIST_URL',
    gen: () => 'http://grist:8484',
    note: 'Base URL of the Grist server used for the "open in sheet" feature',
  },
  {
    key: 'GRIST_API_KEY',
    gen: () => '',
    note: 'Grist API key (create in Grist user menu → API). Empty disables syncing',
  },
  {
    key: 'GRIST_PUBLIC_URL',
    gen: () => '',
    note: 'Origin admin browsers use to open Grist (empty → reuse the app origin)',
  },
  {
    key: 'PUBLIC_SITE_NAME',
    gen: () => 'TADQuiz',
    note: 'Site name shown in UI',
  },
];

function parseArgs(argv) {
  const args = { dir: process.cwd(), forceMissing: false };
  for (let i = 0; i < argv.length; i += 1) {
    if (argv[i] === '--dir') {
      args.dir = path.resolve(argv[i + 1] ?? '.');
      i += 1;
    } else if (argv[i] === '--force-missing') {
      args.forceMissing = true;
    }
  }
  return args;
}

function readExistingKeys(envPath) {
  if (!existsSync(envPath)) return { keys: new Set(), existed: false };
  const text = readFileSync(envPath, 'utf8');
  const keys = new Set();
  for (const line of text.split(/\r?\n/)) {
    const match = /^[#\s]*([A-Za-z_][A-Za-z0-9_]*)\s*=/.exec(line);
    if (match) keys.add(match[1]);
  }
  return { keys, existed: true };
}

function main() {
  const { dir } = parseArgs(process.argv.slice(2));
  const envPath = path.join(dir, '.env');
  const { keys: existing, existed } = readExistingKeys(envPath);

  const missing = ENV_SPEC.filter(
    (spec) => !existing.has(spec.key) && !(spec.key in process.env),
  );
  const providedByEnv = ENV_SPEC.filter(
    (spec) => existing.has(spec.key) === false && spec.key in process.env,
  );

  if (missing.length === 0) {
    console.log(
      `gen-env: .env ${existed ? 'checked' : 'created'} — all ${ENV_SPEC.length} keys present, nothing to do.`,
    );
    if (providedByEnv.length > 0) {
      console.log(
        `gen-env: ${providedByEnv.map((s) => s.key).join(', ')} provided via process environment — skipped.`,
      );
    }
    return;
  }

  mkdirSync(dir, { recursive: true });
  const stamp = new Date().toISOString();
  const lines = [
    existed ? '' : '# TADQuiz environment — generated by scripts/gen-env.mjs',
    `# appended ${stamp}`,
    ...missing.map((spec) => `${spec.key}=${spec.gen()}`),
  ];
  appendFileSync(envPath, `${lines.join('\n')}\n`, 'utf8');

  console.log(`gen-env: ${existed ? 'updated' : 'created'} ${path.relative(process.cwd(), envPath) || '.env'}`);
  for (const spec of missing) {
    const value = spec.secret ? '***random***' : spec.gen();
    console.log(`  + ${spec.key}=${value}  (${spec.note})`);
  }
  console.log(`gen-env: ${ENV_SPEC.length - missing.length} existing keys left untouched.`);
}

main();
